import type { Metadata } from "next";
import "./globals.css";
import Header from "@/comp/layout/header";
import Footer from "@/comp/layout/footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" className="dark">
            <body className="bg-zinc-950 text-zinc-100 min-h-screen">
                <Header />
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
