import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { QueryProvider } from "@/components/providers/query-provider";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" className={cn("dark", "font-sans", geist.variable)}>
            <body className="bg-zinc-950 text-zinc-100 min-h-screen">
                <Header />
                <QueryProvider>{children}</QueryProvider>
                <Footer />
            </body>
        </html>
    );
}
